otelImage: registry-1.docker.io/otel/opentelemetry-collector-contrib:0.112.0
mezmo:
  logs:
    endpoint: https://pipeline.mezmo.com/v1/ccddefc4-8bdd-11ef-a162-eeb610165e9b
    token: gmNkm6iTMp8qDQffMjtLBqTVLFL0BbgO51MlgZZV7zI=
  metrics:
    endpoint: https://pipeline.mezmo.com/v1/ccddefc4-8bdd-11ef-a162-eeb610165e9b
    token: TJKyjktYh5MX2EvKoxQB/BtrIxtD0n5O4iq+deTZaEA=
  traces:
    endpoint: https://pipeline.mezmo.com/v1/ccddefc4-8bdd-11ef-a162-eeb610165e9b
    token: opU3y3Vkj5if4go5rXWzDpwJAb/frVTKmKdWEzIO6zs=