apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: {{ .Release.Namespace }}
data:
  agent-config: | # yaml
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:POD_IP}:4317
          http:
            endpoint: ${env:POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: k8s
              tls_config:
                insecure_skip_verify: true
              scrape_interval: 15s
              kubernetes_sd_configs:
                - role: pod
                  # Scrape pods on same node as agent
                  selectors:
                    - role: pod
                      field: spec.nodeName=${env:NODE_NAME}
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  regex: "true"
                  action: keep
                - action: replace
                  source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
                  target_label: __scheme__
                  regex: (https?)
                - action: replace
                  source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  target_label: __metrics_path__
                  regex: (.+)
                - action: replace
                  source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $$1:$$2
                  target_label: __address__
                # Allow overriding the scrape timeout and interval from pod
                # annotation.
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_timeout]
                  regex: '(.+)'
                  target_label: __scrape_timeout__
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_interval]
                  regex: '(.+)'
                  target_label: __scrape_interval__
    exporters:
      otlp:
        endpoint: "otel-collector.otel.svc.cluster.local:4317"
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 20
      k8sattributes:
        passthrough: true
    extensions:
      health_check:
      zpages: {}
    service:
      extensions: [health_check, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter, k8sattributes]
          exporters: [otlp]
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch, memory_limiter, k8sattributes]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch, memory_limiter, k8sattributes]
          exporters: [otlp]