apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-agent
  name: {{ .Release.Name }}-agent
  namespace: {{ .Release.Namespace }}
spec:
  # Route traffic to agent on local node
  internalTrafficPolicy: Local
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-agent
  type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{ .Release.Name }}-agent
  annotations:
    reloader.stakater.com/auto: "true"
  name: {{ .Release.Name }}-agent
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-agent
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-agent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
    spec:
      containers:
        - command:
            - /otelcol-contrib
            - --config=/conf/agent-config.yaml
          image: {{ .Values.otelImage }}
          imagePullPolicy: IfNotPresent
          name: {{ .Release.Name }}-agent
          ports:
            - containerPort: 55679
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
              name: otlp-grpc
            - containerPort: 4318
              protocol: TCP
              name: otlp-http
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - mountPath: /conf
              name: agent-config-vol
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
      priorityClassName: high # Pod needs to place for metrics to flow
      tolerations:
        - operator: Exists
      volumes:
        - name: agent-config-vol
          configMap:
            name: agent-config
            defaultMode: 420
            items:
              - key: agent-config
                path: agent-config.yaml
      serviceAccountName: {{ .Release.Name }}-collector-sa
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
