apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-collector
  name: {{ .Release.Name }}-collector
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318
    - name: metrics
      port: 8888
  selector:
    app: {{ .Release.Name }}-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-collector
  annotations:
    reloader.stakater.com/auto: "true"
  name: {{ .Release.Name }}-collector
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: {{ .Release.Name }}-collector
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-collector
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
    spec:
      containers:
        - command:
            - /otelcol-contrib
            - --config=/conf/collector-config.yaml
          image: {{ .Values.otelImage }}

          imagePullPolicy: IfNotPresent
          name: {{ .Release.Name }}-collector
          ports:
            - containerPort: 55679
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: 4Gi
          volumeMounts:
            - mountPath: /conf
              name: collector-config-vol
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-collector
            - configMapRef:
                name: {{ .Release.Name }}-collector
                optional: true
      priorityClassName: high # Pod needs to place for metrics to flow
      serviceAccountName: {{ .Release.Name }}-collector
      volumes:
        - name: collector-config-vol
          configMap:
            name: collector-config
            defaultMode: 420
            items:
              - key: collector-config
                path: collector-config.yaml
